apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOYMENT_NAME}
  labels:
    svc: ${DEPLOYMENT_NAME}
spec:
  type: NodePort
  ports:
    - port: ${PORT}
      nodePort: ${NODE_PORT}
      targetPort: ${PORT}
      protocol: TCP
      name: http
  selector:
    app: ${DEPLOYMENT_NAME}
    ENV: ${ENV}

