import vue from '@vitejs/plugin-vue';
import path from 'path';

export default {
   plugins: [vue()],

   resolve: {
      alias: {
         '@': path.resolve(__dirname, './src'),
      },
   },
   css: {
      preprocessorOptions: {
         scss: {
            additionalData: [
               // Make the variables defined in these files available to all components, without requiring an explicit
               // @import of the files themselves
               '@use "../..//assets/styles/variables.scss" as *;',
            ].join('\n'),
         },
      },
   },
   server: {
      port: 3001,
      origin: 'http://localhost:3001',
   },
   base: 'http://localhost:3001/',
   build: {
      minify: false,
      cssCodeSplit: false,
      lib: {},
      rollupOptions: {
         // external modules won't be bundled into your library
         external: ['vue'], // not every external has a global
         resolve: {
            dedupe: ['vue'],
         },
         output: {
            // disable warning on src/index.ts using both default and named export

            // Provide global variables to use in the UMD build
            // for externalized deps (not useful if 'umd' is not in lib.formats)
            globals: {
               vue: 'Vue',
            },
         },
      },
      emptyOutDir: false, // to retain the globalTypes folder generated by tsc
   },
};
