name: Bug report
description: Create a report to help us improve
title: "[BUG]: <Issue title>"
labels: [bug]
body:
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      placeholder: |
        A clear and concise description of what the bug is.
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    id: expected
    validations:
      required: true
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen.
  - type: textarea
    id: actual
    validations:
      required: true
    attributes:
      label: Actual behavior
      placeholder: A clear and concise description of what actually happened.
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      placeholder: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: operating-system
    attributes:
      label: Operating System
      placeholder: |
        **Desktop (please complete the following information):**
        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]

        **Smartphone (please complete the following information):**
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser [e.g. stock browser, safari]
        - Version [e.g. 22]
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
  - type: checkboxes
    id: unique-bug
    attributes:
      label: Is this a unique bug?
      description: |
        If this is a duplicate bug, please close the issue and let us know.
        If this is a unique bug, please let us know.
      options:
        - label: "Yes"
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here.
